#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageProd.Templates
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#line 1 "TicketVentaDesc.cshtml"
using ManageProd.Models.DTO;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "16.10.0.230")]
public partial class TicketVentaDesc : TicketVentaDescBase
{

#line hidden

#line 3 "TicketVentaDesc.cshtml"
public OrdenVentaDTO Model { get; set; }

#line default
#line hidden


public override void Execute()
{
WriteLiteral("\r\n");

WriteLiteral("    <!DOCTYPE html>\r\n\r\n    <html");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral(">\r\n    <head");

WriteLiteral(" runat=\"server\"");

WriteLiteral(">\r\n        <title></title>\r\n    </head>\r\n    <body>\r\n        <form");

WriteLiteral(" id=\"form1\"");

WriteLiteral(" runat=\"server\"");

WriteLiteral(">\r\n            <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n                .tg {\r\n                    border: 0px none white;\r\n          " +
"          width: 400px;\r\n                    height: 100%;\r\n                    " +
"text-align: center;\r\n                }\r\n\r\n                    .tg td {\r\n        " +
"                border-color: white;\r\n                        border-style: none" +
";\r\n                        border-width: 1px;\r\n                        font-fami" +
"ly: \'Lucida Console\';\r\n                        font-size: 10px;\r\n               " +
"         overflow: hidden;\r\n                        word-break: normal;\r\n       " +
"             }\r\n\r\n                    .tg th {\r\n                        border-c" +
"olor: white;\r\n                        border-style: none;\r\n                     " +
"   border-width: 1px;\r\n                        font-family: \'Lucida Console\';\r\n " +
"                       font-size: 10px;\r\n                        font-weight: no" +
"rmal;\r\n                        overflow: hidden;\r\n                        word-b" +
"reak: normal;\r\n                    }\r\n\r\n                    .tg .tg-c3ow {\r\n    " +
"                    border-color: white;\r\n                        border-style: " +
"none;\r\n                        text-align: center;\r\n                        vert" +
"ical-align: top;\r\n                        font-size: 13px;\r\n                    " +
"}\r\n\r\n                    .tg .tg-0pky {\r\n                        border-color: w" +
"hite;\r\n                        border-style: none;\r\n                        text" +
"-align: left;\r\n                        vertical-align: top;\r\n                   " +
"     font-size: 11px;\r\n                    }\r\n\r\n                    .tg .tg-0pky" +
"Center {\r\n                        border-color: white;\r\n                        " +
"border-style: none;\r\n                        text-align: center;\r\n              " +
"          vertical-align: top;\r\n                        font-size: 10px;\r\n      " +
"              }\r\n\r\n                    .tg .tg-0pkyRight {\r\n                    " +
"    border-color: white;\r\n                        border-style: none;\r\n         " +
"               text-align: right;\r\n                        vertical-align: top;\r" +
"\n                        font-size: 10px;\r\n                    }\r\n\r\n            " +
"        .tg .tg-7btt {\r\n                        border-color: white;\r\n          " +
"              border-style: none;\r\n                        font-weight: bold;\r\n " +
"                       text-align: center;\r\n                        vertical-ali" +
"gn: top;\r\n                        font-size: 12px;\r\n                    }\r\n\r\n   " +
"             .Existencias {\r\n                    border-color: white;\r\n         " +
"           border-style: none;\r\n                    text-align: justify;\r\n      " +
"              vertical-align: top;\r\n                    font-size: 10px;\r\n      " +
"              height: 30px;\r\n                }\r\n            </style>\r\n          " +
"  <table");

WriteLiteral(" class=\"tg\"");

WriteLiteral(">\r\n                <thead>\r\n                    <tr>\r\n                        <th" +
"");

WriteLiteral(" class=\"tg-c3ow\"");

WriteLiteral(" colspan=\"8\"");

WriteLiteral("><span");

WriteLiteral(" style=\"font-weight: bold\"");

WriteLiteral(">Comercializadora de Carnes Frias</span></th>\r\n                    </tr>\r\n       " +
"         </thead>\r\n                <tbody>\r\n                    <tr>\r\n          " +
"              <td");

WriteLiteral(" class=\"tg-0pky\"");

WriteLiteral(" colspan=\"8\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" style=\"font-weight: bold\"");

WriteLiteral(">Fecha de venta: </span> ");


#line 101 "TicketVentaDesc.cshtml"
                                                                               Write(Model.FechaVenta);


#line default
#line hidden
WriteLiteral("<br>\r\n                        </td>\r\n                    </tr>\r\n                 " +
"   <tr>\r\n                        <td");

WriteLiteral(" class=\"tg-c3ow\"");

WriteLiteral(" colspan=\"8\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" style=\"font-weight: bold\"");

WriteLiteral(">Ticket de venta </span>\r\n                            <br />\r\n                   " +
"     </td>\r\n                    </tr>\r\n                    <tr>\r\n               " +
"         <td");

WriteLiteral(" class=\"tg-0pky\"");

WriteLiteral(" colspan=\"8\"");

WriteLiteral("><span");

WriteLiteral(" style=\"font-weight: bold\"");

WriteLiteral(">Generado por: </span>");


#line 111 "TicketVentaDesc.cshtml"
                                                                                                        Write(Model.UsuarioCreacion);


#line default
#line hidden
WriteLiteral("</td>\r\n                    </tr>\r\n                    <tr>\r\n                     " +
"   <td");

WriteLiteral(" class=\"tg-0pky\"");

WriteLiteral(" colspan=\"8\"");

WriteLiteral("><span");

WriteLiteral(" style=\"font-weight: bold\"");

WriteLiteral(">Cliente: </span>  ");


#line 114 "TicketVentaDesc.cshtml"
                                                                                                     Write(Model.Cliente);


#line default
#line hidden
WriteLiteral("</td>\r\n                    </tr>\r\n                    <tr>\r\n                     " +
"   <td");

WriteLiteral(" class=\"tg-0pky\"");

WriteLiteral(" colspan=\"8\"");

WriteLiteral("></td>\r\n                    </tr>\r\n                    <tr>\r\n                    " +
"    <td");

WriteLiteral(" class=\"tg-7btt\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">Producto</td>\r\n                        <td");

WriteLiteral(" class=\"tg-7btt\"");

WriteLiteral(">Cantidad</td>\r\n                        <td");

WriteLiteral(" class=\"tg-7btt\"");

WriteLiteral(">Peso</td>\r\n                        <td");

WriteLiteral(" class=\"tg-7btt\"");

WriteLiteral(">Precio</td>\r\n                        <td");

WriteLiteral(" class=\"tg-7btt\"");

WriteLiteral(">Descuento</td>\r\n                        <td");

WriteLiteral(" class=\"tg-7btt\"");

WriteLiteral(">Importe</td>\r\n                    </tr>\r\n");


#line 127 "TicketVentaDesc.cshtml"
                    

#line default
#line hidden

#line 127 "TicketVentaDesc.cshtml"
                     foreach (var item in Model.Productos)
                    {


#line default
#line hidden
WriteLiteral("                        <tr>\r\n                            <td");

WriteLiteral(" class=\"tg-0pky\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">");


#line 130 "TicketVentaDesc.cshtml"
                                                       Write(item.ProductoDesc);


#line default
#line hidden
WriteLiteral("</td>\r\n                            <td");

WriteLiteral(" class=\"tg-0pkyCenter\"");

WriteLiteral(">");


#line 131 "TicketVentaDesc.cshtml"
                                                 Write(item.Cantidad);


#line default
#line hidden
WriteLiteral("</td>\r\n                            <td");

WriteLiteral(" class=\"tg-0pkyCenter\"");

WriteLiteral(">");


#line 132 "TicketVentaDesc.cshtml"
                                                 Write(item.PesoNeto);


#line default
#line hidden
WriteLiteral("</td>\r\n                            <td");

WriteLiteral(" class=\"tg-0pkyCenter\"");

WriteLiteral(">");


#line 133 "TicketVentaDesc.cshtml"
                                                 Write(item.Precio);


#line default
#line hidden
WriteLiteral("</td>\r\n                            <td");

WriteLiteral(" class=\"tg-0pkyCenter\"");

WriteLiteral(">");


#line 134 "TicketVentaDesc.cshtml"
                                                 Write(item.Descuento);


#line default
#line hidden
WriteLiteral("</td>\r\n                            <td");

WriteLiteral(" class=\"tg-0pkyRight \"");

WriteLiteral(">");


#line 135 "TicketVentaDesc.cshtml"
                                                 Write(item.Importe);


#line default
#line hidden
WriteLiteral("</td>\r\n                        </tr>\r\n");


#line 137 "TicketVentaDesc.cshtml"
                    }


#line default
#line hidden
WriteLiteral("                    <tr>\r\n                        <td");

WriteLiteral(" class=\"tg-0pky\"");

WriteLiteral(" colspan=\"8\"");

WriteLiteral("></td>\r\n                    </tr>\r\n                    <tr>\r\n                    " +
"    <td");

WriteLiteral(" class=\"tg-7btt\"");

WriteLiteral(" colspan=\"5\"");

WriteLiteral(">Total a pagar</td>\r\n                        <td");

WriteLiteral(" class=\"tg-7btt\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">");


#line 143 "TicketVentaDesc.cshtml"
                                                   Write(Model.MontoTotal);


#line default
#line hidden
WriteLiteral("</td>\r\n                    </tr>\r\n                    <tr>\r\n                     " +
"   <td");

WriteLiteral(" class=\"tg-0pky\"");

WriteLiteral(" colspan=\"8\"");

WriteLiteral("></td>\r\n                    </tr>\r\n                    <tr>\r\n                    " +
"    <td");

WriteLiteral(" class=\"tg-0pky\"");

WriteLiteral(" colspan=\"8\"");

WriteLiteral(">");


#line 149 "TicketVentaDesc.cshtml"
                                                   Write(Model.MontoLetra);


#line default
#line hidden
WriteLiteral("</td>\r\n                    </tr>\r\n                    <tr>\r\n                     " +
"   <td");

WriteLiteral(" class=\"tg-0pky\"");

WriteLiteral(" colspan=\"8\"");

WriteLiteral("></td>\r\n                    </tr>\r\n                </tbody>\r\n            </table>" +
"\r\n        </form>\r\n    </body>\r\n</html>\r\n");

}
}

// NOTE: this is the default generated helper class. You may choose to extract it to a separate file 
// in order to customize it or share it between multiple templates, and specify the template's base 
// class via the @inherits directive.
public abstract class TicketVentaDescBase
{

		// This field is OPTIONAL, but used by the default implementation of Generate, Write, WriteAttribute and WriteLiteral
		//
		System.IO.TextWriter __razor_writer;

		// This method is OPTIONAL
		//
		/// <summary>Executes the template and returns the output as a string.</summary>
		/// <returns>The template output.</returns>
		public string GenerateString ()
		{
			using (var sw = new System.IO.StringWriter ()) {
				Generate (sw);
				return sw.ToString ();
			}
		}

		// This method is OPTIONAL, you may choose to implement Write and WriteLiteral without use of __razor_writer
		// and provide another means of invoking Execute.
		//
		/// <summary>Executes the template, writing to the provided text writer.</summary>
		/// <param name="writer">The TextWriter to which to write the template output.</param>
		public void Generate (System.IO.TextWriter writer)
		{
			__razor_writer = writer;
			Execute ();
			__razor_writer = null;
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the template output without HTML escaping it.</summary>
		/// <param name="value">The literal value.</param>
		protected void WriteLiteral (string value)
		{
			__razor_writer.Write (value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the TextWriter without HTML escaping it.</summary>
		/// <param name="writer">The TextWriter to which to write the literal.</param>
		/// <param name="value">The literal value.</param>
		protected static void WriteLiteralTo (System.IO.TextWriter writer, string value)
		{
			writer.Write (value);
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a value to the template output, HTML escaping it if necessary.</summary>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected void Write (object value)
		{
			WriteTo (__razor_writer, value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes an object value to the TextWriter, HTML escaping it if necessary.</summary>
		/// <param name="writer">The TextWriter to which to write the value.</param>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected static void WriteTo (System.IO.TextWriter writer, object value)
		{
			if (value == null)
				return;

			var write = value as Action<System.IO.TextWriter>;
			if (write != null) {
				write (writer);
				return;
			}

			//NOTE: a more sophisticated implementation would write safe and pre-escaped values directly to the
			//instead of double-escaping. See System.Web.IHtmlString in ASP.NET 4.0 for an example of this.
			writer.Write(System.Net.WebUtility.HtmlEncode (value.ToString ()));
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to the template output.
		/// </summary>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		protected void WriteAttribute (string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			WriteAttributeTo (__razor_writer, name, prefix, suffix, values);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to a TextWriter.
		/// </summary>
		/// <param name="writer">The TextWriter to which to write the attribute.</param>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		///<remarks>Used by Razor helpers to write attributes.</remarks>
		protected static void WriteAttributeTo (System.IO.TextWriter writer, string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			// this is based on System.Web.WebPages.WebPageExecutingBase
			// Copyright (c) Microsoft Open Technologies, Inc.
			// Licensed under the Apache License, Version 2.0
			if (values.Length == 0) {
				// Explicitly empty attribute, so write the prefix and suffix
				writer.Write (prefix);
				writer.Write (suffix);
				return;
			}

			bool first = true;
			bool wroteSomething = false;

			for (int i = 0; i < values.Length; i++) {
				Tuple<string,object,bool> attrVal = values [i];
				string attPrefix = attrVal.Item1;
				object value = attrVal.Item2;
				bool isLiteral = attrVal.Item3;

				if (value == null) {
					// Nothing to write
					continue;
				}

				// The special cases here are that the value we're writing might already be a string, or that the
				// value might be a bool. If the value is the bool 'true' we want to write the attribute name instead
				// of the string 'true'. If the value is the bool 'false' we don't want to write anything.
				//
				// Otherwise the value is another object (perhaps an IHtmlString), and we'll ask it to format itself.
				string stringValue;
				bool? boolValue = value as bool?;
				if (boolValue == true) {
					stringValue = name;
				} else if (boolValue == false) {
					continue;
				} else {
					stringValue = value as string;
				}

				if (first) {
					writer.Write (prefix);
					first = false;
				} else {
					writer.Write (attPrefix);
				}

				if (isLiteral) {
					writer.Write (stringValue ?? value);
				} else {
					WriteTo (writer, stringValue ?? value);
				}
				wroteSomething = true;
			}
			if (wroteSomething) {
				writer.Write (suffix);
			}
		}
		// This method is REQUIRED. The generated Razor subclass will override it with the generated code.
		//
		///<summary>Executes the template, writing output to the Write and WriteLiteral methods.</summary>.
		///<remarks>Not intended to be called directly. Call the Generate method instead.</remarks>
		public abstract void Execute ();

}
}
#pragma warning restore 1591
