#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageProd.Templates
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#line 1 "TicketCompra.cshtml"
using ManageProd.Models.DTO;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "2.6.0.0")]
public partial class TicketCompra : TicketCompraBase
{

#line hidden

#line 3 "TicketCompra.cshtml"
public OrdenCompraDTO Model { get; set; }

#line default
#line hidden


public override void Execute()
{
WriteLiteral("\n");

WriteLiteral("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org" +
"/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n\n<html");

WriteLiteral(" xmlns=\"http://www.w3.org/1999/xhtml\"");

WriteLiteral(">\n<head");

WriteLiteral(" runat=\"server\"");

WriteLiteral(">\n    <title></title>\n</head>\n<body>\n    <form");

WriteLiteral(" id=\"form1\"");

WriteLiteral(" runat=\"server\"");

WriteLiteral(">\n        <div>\n            <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n                .tg {\r\n                    border: 0px none white;\r\n          " +
"          width: 270px;\r\n                    height: 100%;\r\n                    " +
"text-align: center;\r\n                }\r\n\r\n                    .tg td {\r\n        " +
"                border-color: white;\r\n                        border-style: none" +
";\r\n                        border-width: 1px;\r\n                        font-fami" +
"ly: \'Lucida Console\';\r\n                        font-size: 7px;\r\n                " +
"        overflow: hidden;\r\n                        word-break: normal;\r\n        " +
"            }\r\n\r\n                    .tg th {\r\n                        border-co" +
"lor: white;\r\n                        border-style: none;\r\n                      " +
"  border-width: 1px;\r\n                        font-family: \'Lucida Console\';\r\n  " +
"                      font-size: 7px;\r\n                        font-weight: norm" +
"al;\r\n                        overflow: hidden;\r\n                        word-bre" +
"ak: normal;\r\n                    }\r\n\r\n                    .tg .tg-c3ow {\r\n      " +
"                  border-color: white;\r\n                        border-style: no" +
"ne;\r\n                        text-align: center;\r\n                        vertic" +
"al-align: top;\r\n                        font-family: \'Lucida Console\';\r\n        " +
"                font-size: 9px;\r\n                    }\r\n\r\n                    .t" +
"g .tg-0pky {\r\n                        border-color: white;\r\n                    " +
"    border-style: none;\r\n                        text-align: left;\r\n            " +
"            vertical-align: top;\r\n                        font-family: \'Lucida C" +
"onsole\';\r\n                        font-size: 7px;\r\n                    }\r\n\r\n    " +
"                .tg .tg-0pkyCenter {\r\n                        border-color: whit" +
"e;\r\n                        border-style: none;\r\n                        text-al" +
"ign: center;\r\n                        vertical-align: top;\r\n                    " +
"    font-family: \'Lucida Console\';\r\n                        font-size: 8px;\r\n   " +
"                 }\r\n\r\n                    .tg .tg-0pkyRight {\r\n                 " +
"       border-color: white;\r\n                        border-style: none;\r\n      " +
"                  text-align: right;\r\n                        vertical-align: to" +
"p;\r\n                        font-family: \'Lucida Console\';\r\n                    " +
"    font-size: 7px;\r\n                    }\r\n\r\n                    .tg .tg-7btt {" +
"\r\n                        border-color: white;\r\n                        border-s" +
"tyle: none;\r\n                        font-weight: bold;\r\n                       " +
" text-align: center;\r\n                        vertical-align: top;\r\n            " +
"            font-family: \'Lucida Console\';\r\n                        font-size: 7" +
"px;\r\n                    }\r\n\r\n                .Existencias {\r\n                  " +
"  border-color: white;\r\n                    border-style: none;\r\n               " +
"     text-align: justify;\r\n                    vertical-align: top;\r\n           " +
"         font-size: 7px;\r\n                    font-family: \'Lucida Console\';\r\n  " +
"                  height: 30px;\r\n                }\r\n            </style>\r\n      " +
"      <table");

WriteLiteral(" class=\"tg\"");

WriteLiteral(">\n                <thead>\n                    <tr>\n                        <th");

WriteLiteral(" class=\"tg-c3ow\"");

WriteLiteral(" colspan=\"8\"");

WriteLiteral("><span");

WriteLiteral(" style=\"font-weight: bold\"");

WriteLiteral(">Comercializadora de Carnes Frias</span></th>\n                    </tr>\n         " +
"       </thead>\n                <tbody>\n                    <tr>\n               " +
"         <td");

WriteLiteral(" class=\"tg-0pky\"");

WriteLiteral(" colspan=\"8\"");

WriteLiteral(">\n                            <span");

WriteLiteral(" style=\"font-weight: bold\"");

WriteLiteral(">Fecha de compra: </span> ");


#line 108 "TicketCompra.cshtml"
                                                                                Write(Model.FechaCompra);


#line default
#line hidden
WriteLiteral("<br />\n                        </td>\n                    </tr>\n                  " +
"  <tr>\n                        <td");

WriteLiteral(" class=\"tg-c3ow\"");

WriteLiteral(" colspan=\"8\"");

WriteLiteral(">\n                            <span");

WriteLiteral(" style=\"font-weight: bold\"");

WriteLiteral(">Ticket de compra </span>\n                            <br />\n                    " +
"    </td>\n                    </tr>\n                    <tr>\n                   " +
"     <td");

WriteLiteral(" class=\"tg-0pky\"");

WriteLiteral(" colspan=\"8\"");

WriteLiteral("><span");

WriteLiteral(" style=\"font-weight: bold\"");

WriteLiteral(">Generado por: </span>");


#line 118 "TicketCompra.cshtml"
                                                                                                        Write(Model.UsuarioCreacion);


#line default
#line hidden
WriteLiteral("</td>\n                    </tr>\n                    <tr>\n                        " +
"<td");

WriteLiteral(" class=\"tg-0pky\"");

WriteLiteral(" colspan=\"8\"");

WriteLiteral("><span");

WriteLiteral(" style=\"font-weight: bold\"");

WriteLiteral(">Proveedor: </span>  ");


#line 121 "TicketCompra.cshtml"
                                                                                                       Write(Model.Proveedor);


#line default
#line hidden
WriteLiteral("</td>\n                    </tr>\n");


#line 123 "TicketCompra.cshtml"
                    

#line default
#line hidden

#line 123 "TicketCompra.cshtml"
                     if (@Model.Notas != string.Empty)
                    {


#line default
#line hidden
WriteLiteral("                        <tr>\n                            <td");

WriteLiteral(" class=\"tg-0pky\"");

WriteLiteral(" colspan=\"8\"");

WriteLiteral("><span");

WriteLiteral(" style=\"font-weight: bold\"");

WriteLiteral(">Notas: </span>  ");


#line 126 "TicketCompra.cshtml"
                                                                                                       Write(Model.Notas);


#line default
#line hidden
WriteLiteral("</td>\n                        </tr>\n");


#line 128 "TicketCompra.cshtml"
                    }


#line default
#line hidden
WriteLiteral("                    <tr>\n                        <td");

WriteLiteral(" class=\"tg-7btt\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">Producto</td>\n                        <td");

WriteLiteral(" class=\"tg-7btt\"");

WriteLiteral(">Cant.</td>\r\n                        <td");

WriteLiteral(" class=\"tg-7btt\"");

WriteLiteral(">Peso B.</td>\n                        <td");

WriteLiteral(" class=\"tg-7btt\"");

WriteLiteral(">Peso N.</td>\n                        <td");

WriteLiteral(" class=\"tg-7btt\"");

WriteLiteral(">Precio</td>\n                        <td");

WriteLiteral(" class=\"tg-7btt\"");

WriteLiteral(">Importe</td>\n                    </tr>\n");


#line 137 "TicketCompra.cshtml"
                    

#line default
#line hidden

#line 137 "TicketCompra.cshtml"
                     foreach (var item in Model.Productos)
                    {


#line default
#line hidden
WriteLiteral("                        <tr>\n                            <td");

WriteLiteral(" class=\"tg-0pky\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">");


#line 140 "TicketCompra.cshtml"
                                                       Write(item.ProductoDesc);


#line default
#line hidden
WriteLiteral("</td>\n                            <td");

WriteLiteral(" class=\"tg-0pkyCenter\"");

WriteLiteral(">");


#line 141 "TicketCompra.cshtml"
                                                 Write(item.Cantidad);


#line default
#line hidden
WriteLiteral("</td>\n                            <td");

WriteLiteral(" class=\"tg-0pkyCenter\"");

WriteLiteral(">");


#line 142 "TicketCompra.cshtml"
                                                 Write(item.PesoBruto);


#line default
#line hidden
WriteLiteral("</td>\n                            <td");

WriteLiteral(" class=\"tg-0pkyCenter\"");

WriteLiteral(">");


#line 143 "TicketCompra.cshtml"
                                                 Write(item.PesoNeto);


#line default
#line hidden
WriteLiteral("</td>\n                            <td");

WriteLiteral(" class=\"tg-0pkyCenter\"");

WriteLiteral(">");


#line 144 "TicketCompra.cshtml"
                                                 Write(item.Precio);


#line default
#line hidden
WriteLiteral("</td>\n                            <td");

WriteLiteral(" class=\"tg-0pkyRight \"");

WriteLiteral(">");


#line 145 "TicketCompra.cshtml"
                                                 Write(item.Importe);


#line default
#line hidden
WriteLiteral("</td>\n                        </tr>\n");


#line 147 "TicketCompra.cshtml"
                    }


#line default
#line hidden
WriteLiteral("\n                    <tr>\n                        <td");

WriteLiteral(" class=\"tg-0pky\"");

WriteLiteral(" colspan=\"8\"");

WriteLiteral("></td>\n                    </tr>\n                    <tr>\n                       " +
" <td");

WriteLiteral(" class=\"tg-7btt\"");

WriteLiteral(" colspan=\"5\"");

WriteLiteral(">Total a pagar</td>\n                        <td");

WriteLiteral(" class=\"tg-7btt\"");

WriteLiteral(" colspan=\"3\"");

WriteLiteral(">");


#line 154 "TicketCompra.cshtml"
                                                   Write(Model.MontoTotal);


#line default
#line hidden
WriteLiteral("</td>\n                    </tr>\n                    <tr>\n                        " +
"<td");

WriteLiteral(" class=\"tg-0pky\"");

WriteLiteral(" colspan=\"8\"");

WriteLiteral("></td>\n                    </tr>\n                    <tr>\n                       " +
" <td");

WriteLiteral(" class=\"tg-0pky\"");

WriteLiteral(" colspan=\"8\"");

WriteLiteral(">");


#line 160 "TicketCompra.cshtml"
                                                   Write(Model.MontoLetra);


#line default
#line hidden
WriteLiteral("</td>\n                    </tr>\n                    <tr>\n                        " +
"<td");

WriteLiteral(" class=\"tg-0pky\"");

WriteLiteral(" colspan=\"8\"");

WriteLiteral("></td>\n                    </tr>\n                </tbody>\n            </table>\n  " +
"      </div>\n    </form>\n</body>\n</html>\n\n\n\n\n");

}
}

// NOTE: this is the default generated helper class. You may choose to extract it to a separate file 
// in order to customize it or share it between multiple templates, and specify the template's base 
// class via the @inherits directive.
public abstract class TicketCompraBase
{

		// This field is OPTIONAL, but used by the default implementation of Generate, Write, WriteAttribute and WriteLiteral
		//
		System.IO.TextWriter __razor_writer;

		// This method is OPTIONAL
		//
		/// <summary>Executes the template and returns the output as a string.</summary>
		/// <returns>The template output.</returns>
		public string GenerateString ()
		{
			using (var sw = new System.IO.StringWriter ()) {
				Generate (sw);
				return sw.ToString ();
			}
		}

		// This method is OPTIONAL, you may choose to implement Write and WriteLiteral without use of __razor_writer
		// and provide another means of invoking Execute.
		//
		/// <summary>Executes the template, writing to the provided text writer.</summary>
		/// <param name="writer">The TextWriter to which to write the template output.</param>
		public void Generate (System.IO.TextWriter writer)
		{
			__razor_writer = writer;
			Execute ();
			__razor_writer = null;
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the template output without HTML escaping it.</summary>
		/// <param name="value">The literal value.</param>
		protected void WriteLiteral (string value)
		{
			__razor_writer.Write (value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes a literal value to the TextWriter without HTML escaping it.</summary>
		/// <param name="writer">The TextWriter to which to write the literal.</param>
		/// <param name="value">The literal value.</param>
		protected static void WriteLiteralTo (System.IO.TextWriter writer, string value)
		{
			writer.Write (value);
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>Writes a value to the template output, HTML escaping it if necessary.</summary>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected void Write (object value)
		{
			WriteTo (__razor_writer, value);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>Writes an object value to the TextWriter, HTML escaping it if necessary.</summary>
		/// <param name="writer">The TextWriter to which to write the value.</param>
		/// <param name="value">The value.</param>
		/// <remarks>The value may be a Action<System.IO.TextWriter>, as returned by Razor helpers.</remarks>
		protected static void WriteTo (System.IO.TextWriter writer, object value)
		{
			if (value == null)
				return;

			var write = value as Action<System.IO.TextWriter>;
			if (write != null) {
				write (writer);
				return;
			}

			//NOTE: a more sophisticated implementation would write safe and pre-escaped values directly to the
			//instead of double-escaping. See System.Web.IHtmlString in ASP.NET 4.0 for an example of this.
			writer.Write(System.Net.WebUtility.HtmlEncode (value.ToString ()));
		}

		// This method is REQUIRED, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to the template output.
		/// </summary>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		protected void WriteAttribute (string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			WriteAttributeTo (__razor_writer, name, prefix, suffix, values);
		}

		// This method is REQUIRED if the template contains any Razor helpers, but you may choose to implement it differently
		//
		/// <summary>
		/// Conditionally writes an attribute to a TextWriter.
		/// </summary>
		/// <param name="writer">The TextWriter to which to write the attribute.</param>
		/// <param name="name">The name of the attribute.</param>
		/// <param name="prefix">The prefix of the attribute.</param>
		/// <param name="suffix">The suffix of the attribute.</param>
		/// <param name="values">Attribute values, each specifying a prefix, value and whether it's a literal.</param>
		///<remarks>Used by Razor helpers to write attributes.</remarks>
		protected static void WriteAttributeTo (System.IO.TextWriter writer, string name, string prefix, string suffix, params Tuple<string,object,bool>[] values)
		{
			// this is based on System.Web.WebPages.WebPageExecutingBase
			// Copyright (c) Microsoft Open Technologies, Inc.
			// Licensed under the Apache License, Version 2.0
			if (values.Length == 0) {
				// Explicitly empty attribute, so write the prefix and suffix
				writer.Write (prefix);
				writer.Write (suffix);
				return;
			}

			bool first = true;
			bool wroteSomething = false;

			for (int i = 0; i < values.Length; i++) {
				Tuple<string,object,bool> attrVal = values [i];
				string attPrefix = attrVal.Item1;
				object value = attrVal.Item2;
				bool isLiteral = attrVal.Item3;

				if (value == null) {
					// Nothing to write
					continue;
				}

				// The special cases here are that the value we're writing might already be a string, or that the 
				// value might be a bool. If the value is the bool 'true' we want to write the attribute name instead
				// of the string 'true'. If the value is the bool 'false' we don't want to write anything.
				//
				// Otherwise the value is another object (perhaps an IHtmlString), and we'll ask it to format itself.
				string stringValue;
				bool? boolValue = value as bool?;
				if (boolValue == true) {
					stringValue = name;
				} else if (boolValue == false) {
					continue;
				} else {
					stringValue = value as string;
				}

				if (first) {
					writer.Write (prefix);
					first = false;
				} else {
					writer.Write (attPrefix);
				}

				if (isLiteral) {
					writer.Write (stringValue ?? value);
				} else {
					WriteTo (writer, stringValue ?? value);
				}
				wroteSomething = true;
			}
			if (wroteSomething) {
				writer.Write (suffix);
			}
		}
		// This method is REQUIRED. The generated Razor subclass will override it with the generated code.
		//
		///<summary>Executes the template, writing output to the Write and WriteLiteral methods.</summary>.
		///<remarks>Not intended to be called directly. Call the Generate method instead.</remarks>
		public abstract void Execute ();

}
}
#pragma warning restore 1591
